/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Exodia 🇵🇸",
  "tagline": "Old website",
  "url": "https://github.com",
  "baseUrl": "/exodia-website/",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "logos/exodia-cyan.png",
  "organizationName": "Exodia-OS",
  "projectName": "exodia-website",
  "deploymentBranch": "gh-pages",
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Exodia OS",
      "logo": {
        "alt": "Exodia Logo",
        "src": "logos/exodia-cyan.png",
        "href": "https://exodia-os.github.io"
      },
      "hideOnScroll": false,
      "items": []
    },
    "footer": {
      "style": "dark",
      "links": [],
      "copyright": "Exodia OS is licensed under the GPl-3 License © 2024 Exodia OS Development & Cyb3rTh1eveZ Team"
    },
    "prism": {
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/home/o0xwolf/GitHub/Exodia-Repos/websites/exodia-website/sidebars.js",
          "sidebarCollapsible": true
        },
        "theme": {
          "customCss": "/home/o0xwolf/GitHub/Exodia-Repos/websites/exodia-website/src/css/style.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
