/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Exodia",
  "tagline": "OS For Cyber Security",
  "url": "https://github.com",
  "baseUrl": "/exodia-website/",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/Exodia.png",
  "organizationName": "Exodia-OS",
  "projectName": "exodia-website",
  "deploymentBranch": "gh-pages",
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Exodia OS",
      "logo": {
        "alt": "Exodia Logo",
        "src": "img/Exodia.png"
      },
      "items": [
        {
          "to": "quickstart/install",
          "label": "Wiki",
          "position": "left",
          "sidebarId": "config"
        },
        {
          "to": "Keybinding",
          "label": "Keybinding",
          "position": "left",
          "sidebarId": "config"
        },
        {
          "to": "themes/themelist",
          "label": "Themes",
          "position": "left",
          "sidebarId": "themesPage"
        },
        {
          "href": "https://github.com/Exodia-OS",
          "position": "right"
        },
        {
          "href": "https://discord.gg/wPDyfR5AV9",
          "position": "right"
        },
        {
          "href": "https://t.me/exodiaos",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Developers",
          "items": [
            {
              "label": "Team",
              "href": "https://exodia-os.github.io/team/",
              "position": "center"
            },
            {
              "label": "Publisher GitHub",
              "href": "https://github.com/mmsaeed509",
              "position": "right"
            },
            {
              "label": "Publisher LinkedIn",
              "href": "https://www.linkedin.com/in/mahmoud-mohamed-a934b21a5/",
              "position": "right"
            },
            {
              "label": "Publisher",
              "href": "https://portfolio-mmsaeed509.vercel.app/",
              "position": "right"
            }
          ]
        },
        {
          "title": "Editions src code",
          "items": [
            {
              "label": "Home",
              "href": "https://github.com/Exodia-OS/exodia-home-ISO",
              "position": "center"
            },
            {
              "label": "Predator",
              "href": "https://github.com/Exodia-OS/exodia-predator",
              "position": "center"
            },
            {
              "label": "Wireless",
              "href": "https://github.com/Exodia-OS/exodia-wireless",
              "position": "center"
            }
          ]
        },
        {
          "title": "Issues",
          "items": [
            {
              "label": "Home",
              "href": "https://github.com/Exodia-OS/exodia-home-ISO/issues",
              "position": "center"
            },
            {
              "label": "Predator",
              "href": "https://github.com/Exodia-OS/exodia-predator/issues",
              "position": "center"
            },
            {
              "label": "Wireless",
              "href": "https://github.com/Exodia-OS/exodia-wireless/issues",
              "position": "center"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2023 Mahmoud Mohamed | Cyb3rTh1eveZ Team"
    },
    "prism": {
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/home/ozil/GitHub/Exodia-Repos/Exodia-Websites/exodia-website/sidebars.js",
          "sidebarCollapsible": true
        },
        "theme": {
          "customCss": "/home/ozil/GitHub/Exodia-Repos/Exodia-Websites/exodia-website/src/css/style.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
