/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Exodia",
  "tagline": "OS For Cyber Security",
  "url": "https://github.com",
  "baseUrl": "/exodia-website/",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/Exodia.png",
  "organizationName": "Exodia-OS",
  "projectName": "exodia-website",
  "deploymentBranch": "gh-pages",
  "themeConfig": {
    "colorMode": {
      "respectPrefersColorScheme": true,
      "defaultMode": "light",
      "disableSwitch": false
    },
    "navbar": {
      "title": "Exodia OS",
      "logo": {
        "alt": "Exodia Logo",
        "src": "img/Exodia.png"
      },
      "items": [
        {
          "to": "credits",
          "sidebarId": "config",
          "position": "left",
          "label": "Team"
        },
        {
          "to": "quickstart/install",
          "label": "Wiki",
          "position": "left",
          "sidebarId": "config"
        },
        {
          "to": "Keybinding",
          "label": "Keybinding",
          "position": "left",
          "sidebarId": "config"
        },
        {
          "to": "themes/themelist",
          "label": "Themes",
          "position": "left",
          "sidebarId": "themesPage"
        },
        {
          "href": "https://github.com/Exodia-OS",
          "position": "right"
        },
        {
          "href": "https://discord.gg/6uX97aWN",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Publisher",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/mmsaeed509",
              "position": "right"
            },
            {
              "label": "Facebook",
              "href": "https://www.facebook.com/engrody.linux.5",
              "position": "right"
            },
            {
              "label": "Instagram",
              "href": "https://www.instagram.com/mmsaeed509/?theme=dark",
              "position": "right"
            }
          ]
        },
        {
          "items": [
            {
              "label": "reddit",
              "href": "https://www.reddit.com/user/mmsaeed509",
              "position": "center"
            },
            {
              "label": "LinkedIn",
              "href": "https://www.linkedin.com/in/mahmoud-mohamed-a934b21a5/",
              "position": "center"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/Mahmoudzil4",
              "position": "center"
            }
          ],
          "title": null
        },
        {
          "items": [
            {
              "label": "discord",
              "href": "https://discordapp.com/users/528010173403365377",
              "position": "left"
            },
            {
              "label": "GitLab",
              "href": "https://gitlab.com/mmsaeed509",
              "position": "left"
            }
          ],
          "title": null
        }
      ],
      "copyright": "Copyright © 2022 Mahmoud Mohamed | Cyb3rTh1eveZ Team"
    },
    "prism": {
      "additionalLanguages": []
    },
    "docs": {
      "versionPersistence": "localStorage"
    },
    "metadata": [],
    "hideableSidebar": false,
    "autoCollapseSidebarCategories": false,
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/home/ozil/GitHub/exodia-website/sidebars.js",
          "sidebarCollapsible": true
        },
        "theme": {
          "customCss": "/home/ozil/GitHub/exodia-website/src/css/style.css"
        }
      }
    ]
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
