export default {
  '05b34754': [() => import(/* webpackChunkName: '05b34754' */ '@site/docs/themes/themelist.md'), '@site/docs/themes/themelist.md', require.resolveWeak('@site/docs/themes/themelist.md')],
  '07fa6354': [() => import(/* webpackChunkName: '07fa6354' */ '@site/docs/themes/glassy.md'), '@site/docs/themes/glassy.md', require.resolveWeak('@site/docs/themes/glassy.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '2872d7a0': [() => import(/* webpackChunkName: '2872d7a0' */ '@site/docs/quickstart/post-install.md'), '@site/docs/quickstart/post-install.md', require.resolveWeak('@site/docs/quickstart/post-install.md')],
  '381d9fdb': [() => import(/* webpackChunkName: '381d9fdb' */ '@site/docs/quickstart/install.md'), '@site/docs/quickstart/install.md', require.resolveWeak('@site/docs/quickstart/install.md')],
  '50fdedd3': [() => import(/* webpackChunkName: '50fdedd3' */ '@site/docs/Keybinding.md'), '@site/docs/Keybinding.md', require.resolveWeak('@site/docs/Keybinding.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '6e187dbf': [() => import(/* webpackChunkName: '6e187dbf' */ '@site/docs/credit.md'), '@site/docs/credit.md', require.resolveWeak('@site/docs/credit.md')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'f354ecb7': [() => import(/* webpackChunkName: 'f354ecb7' */ '/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json'), '/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json', require.resolveWeak('/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-docs/default/plugin-route-context-module-100.json')],
  'f3cd8cd4': [() => import(/* webpackChunkName: 'f3cd8cd4' */ '/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json'), '/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json', require.resolveWeak('/home/ozil/GitHub/exodia-website/.docusaurus/docusaurus-plugin-content-pages/default/plugin-route-context-module-100.json')],};
